export type VerifiedPracticeTest7Math2Content={lines:string[];needsVisual?:boolean}
const q=(lines:string[],needsVisual=false):VerifiedPracticeTest7Math2Content=>({lines,needsVisual})

export const VERIFIED_PRACTICE_TEST_7_MATH2:Record<number,VerifiedPracticeTest7Math2Content>={
  1:q([
    "A total of 165 people contributed to a charity event as either a donor or a volunteer. 130 people contributed as a donor. How many people contributed as a volunteer?",
    "A) $35$",
    "B) $130$",
    "C) $165$",
    "D) $330$",
  ]),
  2:q([
    "There are 250 trees in a park. Of these trees, $6\\%$ are birch trees. How many birch trees are in the park?",
    "A) $6$",
    "B) $15$",
    "C) $75$",
    "D) $244$",
  ]),
  3:q([
    "The graph of the quadratic function $y=f(x)$ is shown. What is the vertex of the graph?",
    "A) $(0,-2)$",
    "B) $(0,-3)$",
    "C) $(0,2)$",
    "D) $(0,3)$",
  ],true),
  4:q([
    "The number of raccoons in a 131-square-mile area is estimated to be 2,358. What is the estimated population density, in raccoons per square mile, of this area?",
    "A) $18$",
    "B) $131$",
    "C) $149$",
    "D) $2{,}376$",
  ]),
  5:q([
    "$$-11,\ -9,\ 26$$",
    "A data set of three numbers is shown. If a number from this data set is selected at random, what is the probability of selecting a positive number?",
    "A) $0$",
    "B) $\\frac{1}{3}$",
    "C) $\\frac{2}{3}$",
    "D) $1$",
  ]),
  6:q([
    "$$f(x)=45x+600$$",
    "The function $f$ gives the monthly fee $f(x)$, in dollars, a facility charges to keep $x$ crates in storage. What is the monthly fee, in dollars, the facility charges to keep 50 crates in storage?",
  ]),
  7:q([
    "$$f(x)=5\\left(\\frac{1}{4}-x\\right)^2+\\frac{11}{4}$$",
    "The function $f$ is defined by the given equation. What is the value of $f\\left(\\frac{1}{4}\\right)$?",
  ]),
  8:q([
    "If $8x=6$, what is the value of $72x$?",
    "A) $3$",
    "B) $15$",
    "C) $54$",
    "D) $57$",
  ]),
  9:q([
    "Which expression is equivalent to $23x^3+2x^2+9x$?",
    "A) $23x(x^2+2x+9)$",
    "B) $9x(23x^3+2x^2+1)$",
    "C) $x(23x^2+2x+9)$",
    "D) $34(x^3+x^2+x)$",
  ]),
  10:q([
    "Which expression is equivalent to $(9x^3+5x+7)+(6x^3+5x^2-5)$?",
    "A) $15x^6+5x^2-5x-35$",
    "B) $15x^3+10x^2+2$",
    "C) $15x^6+5x^2+5x+2$",
    "D) $15x^3+5x^2+5x+2$",
  ]),
  11:q([
    "At a state fair, attendees can win tokens that are worth a different number of points depending on the shape. One attendee won $S$ square tokens and $C$ circle tokens worth a total of 1,120 points. The equation $80S+90C=1{,}120$ represents this situation. How many more points is a circle token worth than a square token?",
    "A) $950$",
    "B) $90$",
    "C) $80$",
    "D) $10$",
  ]),
  12:q([
    "In the given scatterplot, a line of best fit for the data is shown.",
    "Which of the following is closest to the slope of the line of best fit shown?",
    "A) $0$",
    "B) $\\frac{1}{2}$",
    "C) $1$",
    "D) $2$",
  ],true),
  13:q([
    "A circle has a radius of 2.1 inches. The area of the circle is $b\\pi$ square inches, where $b$ is a constant. What is the value of $b$?",
  ]),
  14:q([
    "In triangle $XYZ$, angle $Y$ is a right angle, point $P$ lies on $\\overline{XZ}$, and point $Q$ lies on $\\overline{YZ}$ such that $\\overline{PQ}$ is parallel to $\\overline{XY}$. If the measure of angle $XZY$ is $63°$, what is the measure, in degrees, of angle $XPQ$?",
  ]),
  15:q([
    "An investment account was opened with an initial value of $890. The value of the account doubled every 10 years. Which equation represents the value of the account $M(t)$, in dollars, $t$ years after the account was opened?",
    "A) $M(t)=890\\left(\\frac{1}{2}\\right)^{t/10}$",
    "B) $M(t)=890\\left(\\frac{1}{10}\\right)^{t/2}$",
    "C) $M(t)=890(2)^{t/10}$",
    "D) $M(t)=890(10)^{t/2}$",
  ]),
  16:q([
    "$$y<x$$",
    "$$x<22$$",
    "For which of the following tables are all the values of $x$ and their corresponding values of $y$ solutions to the given system of inequalities?",
    "A)",
    "x\ty",
    "19\t18",
    "20\t19",
    "21\t20",
    "B)",
    "x\ty",
    "19\t20",
    "20\t21",
    "21\t22",
    "C)",
    "x\ty",
    "23\t22",
    "24\t23",
    "25\t24",
    "D)",
    "x\ty",
    "23\t24",
    "24\t25",
    "25\t26",
  ]),
  17:q([
    "Which expression is equivalent to $\\frac{h^{15}q^7}{h^5q^{21}}$, where $h>0$ and $q>0$?",
    "A) $\\frac{h^{10}}{q^{14}}$",
    "B) $\\frac{h^3}{q^3}$",
    "C) $h^{10}q^{14}$",
    "D) $h^3q^3$",
  ]),
  18:q([
    "$$\\begin{aligned}3y&=4x+17\\\\-3y&=9x-23\\end{aligned}$$",
    "The solution to the given system of equations is $(x,y)$. What is the value of $39x$?",
    "A) $-18$",
    "B) $-6$",
    "C) $6$",
    "D) $18$",
  ]),
  19:q([
    "$$h(t)=-16t^2+b$$",
    "The function $h$ estimates an object's height, in feet, above the ground $t$ seconds after the object is dropped, where $b$ is a constant. The function estimates that the object is 3,364 feet above the ground when it is dropped at $t=0$. Approximately how many seconds after being dropped does the function estimate the object will hit the ground?",
    "A) $7.25$",
    "B) $14.50$",
    "C) $105.13$",
    "D) $210.25$",
  ]),
  20:q([
    "$$2x^2-8x-7=0$$",
    "One solution to the given equation can be written as $\\frac{8-\\sqrt{k}}{4}$, where $k$ is a constant. What is the value of $k$?",
  ]),
  21:q([
    "A line intersects two parallel lines, forming four acute angles and four obtuse angles. The measure of one of the acute angles is $(9x-560)°$. The sum of the measures of one of the acute angles and three of the obtuse angles is $(-18x+w)°$. What is the value of $w$?",
  ]),
  22:q([
    "x\tf(x)",
    "-4\t0",
    "-19/5\t1",
    "-18/5\t2",
    "For the linear function $f$, the table shows three values of $x$ and their corresponding values of $f(x)$. If $h(x)=f(x)-13$, which equation defines $h$?",
    "A) $h(x)=5x-4$",
    "B) $h(x)=5x+7$",
    "C) $h(x)=5x+9$",
    "D) $h(x)=5x+20$",
  ]),
  23:q([
    "The linear function $g$ is defined by $g(x)=b-15x$, where $b$ is a constant. If $g(c+7)=\\frac{c}{4}$, where $c$ is a constant, which of the following expressions represents the value of $b$?",
    "A) $\\frac{15c}{4}$",
    "B) $\\frac{19c}{4}+7$",
    "C) $\\frac{61c}{4}+105$",
    "D) $15c+105$",
  ]),
  24:q([
    "In triangle $XYZ$, angle $Z$ is a right angle and the length of $\\overline{YZ}$ is 24 units. If $\\tan X=\\frac{12}{35}$, what is the perimeter, in units, of triangle $XYZ$?",
    "A) $188$",
    "B) $168$",
    "C) $84$",
    "D) $71$",
  ]),
  25:q([
    "$$x^2+14x+y^2=6y+109$$",
    "In the $xy$-plane, the graph of the given equation is a circle. What is the length of the circle's radius?",
    "A) $\\sqrt{109}$",
    "B) $\\sqrt{149}$",
    "C) $\\sqrt{167}$",
    "D) $\\sqrt{341}$",
  ]),
  26:q([
    "The speed of a vehicle is increasing at a rate of 7.3 meters per second squared. What is this rate, in miles per minute squared, rounded to the nearest tenth? (Use 1 mile = 1,609 meters.)",
    "A) $0.3$",
    "B) $16.3$",
    "C) $195.8$",
    "D) $220.4$",
  ]),
  27:q([
    "$$\\begin{aligned}y&=-2.5\\\\y&=x^2+8x+k\\end{aligned}$$",
    "In the given system of equations, $k$ is a positive integer constant. The system has no real solutions. What is the least possible value of $k$?",
  ]),
}

export function verifiedPracticeTest7Math2Content(questionNumber:number){return VERIFIED_PRACTICE_TEST_7_MATH2[questionNumber]}
