export type VerifiedPracticeTest7MathContent={lines:string[];needsVisual?:boolean}
const q=(lines:string[],needsVisual=false):VerifiedPracticeTest7MathContent=>({lines,needsVisual})

export const VERIFIED_PRACTICE_TEST_7_MATH1:Record<number,VerifiedPracticeTest7MathContent>={
  1:q([
    "The scatterplot shows the temperature, in degrees Fahrenheit (°F), and the distance above sea level, in feet, measured at 6 locations on Mount Jefferson. A line of best fit is also shown.",
    "At a distance of 4,000 feet above sea level, what is the temperature, in °F, predicted by the line of best fit?",
    "A) $47$",
    "B) $35$",
    "C) $25$",
    "D) $0$",
  ],true),
  2:q([
    "Rectangle $P$ has an area of 72 square inches. If a rectangle with an area of 20 square inches is removed from rectangle $P$, what is the area, in square inches, of the resulting figure?",
    "A) $92$",
    "B) $84$",
    "C) $80$",
    "D) $52$",
  ]),
  3:q([
    "$$|p|+61=65$$",
    "Which value is a solution to the given equation?",
    "A) $\\frac{65}{61}$",
    "B) $4$",
    "C) $126$",
    "D) $130$",
  ]),
  4:q([
    "Lorenzo purchased a box of cereal and some strawberries at the grocery store. Lorenzo paid $2 for the box of cereal and $1.90 per pound for the strawberries. If Lorenzo paid a total of $9.60 for the box of cereal and the strawberries, which of the following equations can be used to find $p$, the number of pounds of strawberries Lorenzo purchased? (Assume there is no sales tax.)",
    "A) $1.90p+2=9.60$",
    "B) $1.90p-2=9.60$",
    "C) $1.90+2p=9.60$",
    "D) $1.90-2p=9.60$",
  ]),
  5:q([
    "The bar graph summarizes the charge, in kilowatt-hours (kWh), a battery received each day for 15 days.",
    "For how many of these 15 days did the battery receive a charge of 0 kWh?",
    "A) $0$",
    "B) $1$",
    "C) $4$",
    "D) $6$",
  ],true),
  6:q([
    "A line in the $xy$-plane has a slope of 9 and passes through the point $(0,-5)$. The equation $y=px+r$ defines the line, where $p$ and $r$ are constants. What is the value of $p$?",
  ]),
  7:q([
    "What is an $x$-coordinate of an $x$-intercept of the graph of $y=3(x-14)(x+5)(x+4)$ in the $xy$-plane?",
  ]),
  8:q([
    "The graph shown gives the estimated value, in dollars, of a tablet as a function of the number of months since it was purchased. What is the best interpretation of the $y$-intercept of the graph in this context?",
    "A) The estimated value of the tablet was $225 when it was purchased.",
    "B) The estimated value of the tablet 24 months after it was purchased was $225.",
    "C) The estimated value of the tablet had decreased by $225 in the 24 months after it was purchased.",
    "D) The estimated value of the tablet decreased by approximately 2.25% each year after it was purchased.",
  ],true),
  9:q([
    "Triangles $EFG$ and $JKL$ are congruent, where $E$, $F$, and $G$ correspond to $J$, $K$, and $L$, respectively. The measure of angle $E$ is $45°$ and the measure of angle $F$ is $20°$. What is the measure of angle $J$?",
    "A) $20°$",
    "B) $45°$",
    "C) $135°$",
    "D) $160°$",
  ]),
  10:q([
    "The function $f$ is defined by $f(x)=\\frac{1}{2}(x+6)$. What is the value of $f(4)$?",
    "A) $20$",
    "B) $12$",
    "C) $10$",
    "D) $5$",
  ]),
  11:q([
    "The graph of a system of an absolute value function and a linear function is shown. What is the solution $(x,y)$ to this system of two equations?",
    "A) $(0,8)$",
    "B) $(\\frac{7}{2},\\frac{9}{2})$",
    "C) $(-\\frac{7}{2},\\frac{9}{2})$",
    "D) $(-3,4)$",
  ],true),
  12:q([
    "$$y=6x+3$$",
    "One of the two equations in a system of linear equations is given. The system has infinitely many solutions. Which equation could be the second equation in this system?",
    "A) $y=2(6x)+3$",
    "B) $y=2(6x+3)$",
    "C) $2y=2(6x)+3$",
    "D) $2y=2(6x+3)$",
  ]),
  13:q([
    "If $\\frac{6}{7}p+18=54$, what is the value of $7p$?",
  ]),
  14:q([
    "$$\\begin{aligned}y&=9x+12\\\\x+7y&=20\\end{aligned}$$",
    "The solution to the given system of equations is $(x,y)$. What is the value of $y$?",
  ]),
  15:q([
    "A circle in the $xy$-plane has the equation $(x-13)^2+(y-k)^2=64$. Which of the following gives the center of the circle and its radius?",
    "A) The center is at $(13,k)$ and the radius is 8.",
    "B) The center is at $(k,13)$ and the radius is 8.",
    "C) The center is at $(k,13)$ and the radius is 64.",
    "D) The center is at $(13,k)$ and the radius is 64.",
  ]),
  16:q([
    "The function $f$ is defined by $f(x)=|x-4x|$. What value of $a$ satisfies $f(5)-f(a)=-15$?",
    "A) $-20$",
    "B) $5$",
    "C) $10$",
    "D) $45$",
  ]),
  17:q([
    "For the exponential function $f$, the value of $f(0)$ is $c$, where $c$ is a constant. Of the following equations that define the function $f$, which equation shows the value of $c$ as the coefficient or the base?",
    "A) $f(x)=22(1.5)^{x+1}$",
    "B) $f(x)=33(1.5)^x$",
    "C) $f(x)=49.5(1.5)^{x-1}$",
    "D) $f(x)=74.25(1.5)^{x-2}$",
  ]),
  18:q([
    "The function $f(t)=40{,}000(2)^{t/790}$ gives the number of bacteria in a population $t$ minutes after an initial observation. How much time, in minutes, does it take for the number of bacteria in the population to double?",
    "A) $2$",
    "B) $790$",
    "C) $1{,}580$",
    "D) $40{,}000$",
  ]),
  19:q([
    "$$\\frac{12}{n}-\\frac{2}{t}=-\\frac{2}{w}$$",
    "The given equation relates the variables $n$, $t$, and $w$, where $n>0$, $t>0$, and $w>t$. Which expression is equivalent to $n$?",
    "A) $12tw$",
    "B) $6(t-w)$",
    "C) $\\frac{w-t}{6tw}$",
    "D) $\\frac{6tw}{w-t}$",
  ]),
  20:q([
    "During a study, the temperature, in degrees Celsius (°C), of the air in a chamber was recorded to the nearest integer at certain times. The scatterplot shows the recorded temperature $y$, in °C, of the air in the chamber $x$ minutes after the start of the study.",
    "What was the average rate of change, in °C per minute, of the recorded temperature of the air in the chamber from $x=5$ to $x=7$?",
  ],true),
  21:q([
    "In August, a car dealer completed 15 more than 3 times the number of sales the car dealer completed in September. In August and September, the car dealer completed 363 sales. How many sales did the car dealer complete in September?",
  ]),
  22:q([
    "Points $Q$ and $R$ lie on a circle with center $P$. The radius of this circle is 9 inches. Triangle $PQR$ has a perimeter of 31 inches. What is the length, in inches, of $\\overline{QR}$?",
    "A) $13\\sqrt{2}$",
    "B) $13$",
    "C) $9\\sqrt{2}$",
    "D) $9$",
  ]),
  23:q([
    "In a set of four consecutive odd integers, where the integers are ordered from least to greatest, the first integer is represented by $x$. The product of 12 and the fourth odd integer is at most 26 less than the sum of the first and third odd integers. Which inequality represents this situation?",
    "A) $12(x+6)\\le x+(x+4)-26$",
    "B) $12(x+6)\\ge26-(x+(x+4))$",
    "C) $12(x+4)\\le x+(x+3)-26$",
    "D) $12(x+4)\\ge26-(x+(x+3))$",
  ]),
  24:q([
    "x\ty",
    "-2s\t24",
    "-s\t21",
    "s\t15",
    "The table shows three values of $x$ and their corresponding values of $y$, where $s$ is a constant. There is a linear relationship between $x$ and $y$. Which of the following equations represents this relationship?",
    "A) $sx+3y=18s$",
    "B) $3x+sy=18s$",
    "C) $3x+sy=18$",
    "D) $sx+3y=18$",
  ]),
  25:q([
    "Which of the following expressions is equivalent to $(\\sin24°)(\\cos66°)+(\\cos24°)(\\sin66°)$?",
    "A) $2(\\cos66°)(\\sin24°)$",
    "B) $2(\\cos66°)+2(\\cos24°)$",
    "C) $(\\cos66°)^2+(\\cos24°)^2$",
    "D) $(\\cos66°)^2+(\\sin24°)^2$",
  ]),
  26:q([
    "The cost of renting a carpet cleaner is $52 for the first day and $26 for each additional day. Which of the following functions gives the cost $C(d)$, in dollars, of renting the carpet cleaner for $d$ days, where $d$ is a positive integer?",
    "A) $C(d)=26d+26$",
    "B) $C(d)=26d+52$",
    "C) $C(d)=52d-26$",
    "D) $C(d)=52d+78$",
  ]),
  27:q([
    "$$f(x)=(x-2)(x+15)$$",
    "The function $f$ is defined by the given equation. For what value of $x$ does $f(x)$ reach its minimum?",
  ]),
}

export function verifiedPracticeTest7Math1Content(questionNumber:number){return VERIFIED_PRACTICE_TEST_7_MATH1[questionNumber]}
