export type VerifiedPracticeTest5MathContent={lines:string[];needsVisual?:boolean;imageFallback?:boolean}
const q=(lines:string[],needsVisual=false):VerifiedPracticeTest5MathContent=>({lines,needsVisual})

export const VERIFIED_PRACTICE_TEST_5_MATH1:Record<number,VerifiedPracticeTest5MathContent>={
  1:q(['The graph of a system of a linear equation and a nonlinear equation is shown. What is the solution $(x,y)$ to this system?','A) $(0,0)$','B) $(0,4)$','C) $(4,5)$','D) $(5,0)$'],true),
  2:q(['On the first day of a semester, a film club has 90 members. Each day after the first day of the semester, 10 new members join the film club. If no members leave the film club, how many total members will the film club have 4 days after the first day of the semester?','A) 400','B) 130','C) 94','D) 90']),
  3:q(['The graph of the linear function $f$ is shown, where $y=f(x)$. What is the $y$-intercept of the graph of $f$?','A) $(0,0)$','B) $\\left(0,-\\frac{16}{11}\\right)$','C) $(0,-8)$','D) $(0,8)$'],true),
  4:q(['$$\\begin{aligned}s+7r&=27\\\\r&=3\\end{aligned}$$','What is the solution $(r,s)$ to the given system of equations?','A) $(6,3)$','B) $(3,6)$','C) $(3,27)$','D) $(27,3)$']),
  5:q(['The table shows selected values from function $f$.','x f(x)','−1 16','0 17','1 18','2 19','Which of the following is the best description of function $f$?','A) Decreasing linear','B) Increasing linear','C) Decreasing exponential','D) Increasing exponential']),
  6:q(['The graph of a system of linear equations is shown. The solution to the system is $(x,y)$. What is the value of $x$?'],true),
  7:q(['23, 27, 27, 32, 35, 36, 52','What is the range of the 7 scores shown?']),
  8:q(['Note: Figure not drawn to scale.','In the figure, line $m$ is parallel to line $n$, and line $k$ intersects both lines. Which of the following statements is true?','A) The value of $x$ is less than 145.','B) The value of $x$ is greater than 145.','C) The value of $x$ is equal to 145.','D) The value of $x$ cannot be determined.'],true),
  9:q(['The equation $x+y=1{,}440$ represents the number of minutes of daylight (between sunrise and sunset), $x$, and the number of minutes of non-daylight, $y$, on a particular day in Oak Park, Illinois. If this day has 670 minutes of daylight, how many minutes of non-daylight does it have?','A) 670','B) 770','C) 1,373','D) 1,440']),
  10:q(['Scott selected 20 employees at random from all 400 employees at a company. He found that 16 of the employees in this sample are enrolled in exactly three professional development courses this year. Based on Scott’s findings, which of the following is the best estimate of the number of employees at the company who are enrolled in exactly three professional development courses this year?','A) 4','B) 320','C) 380','D) 384']),
  11:q(['If $4x-28=-24$, what is the value of $x-7$?','A) −24','B) −22','C) −6','D) −1']),
  12:q(['For a snowstorm in a certain town, the minimum rate of snowfall recorded was 0.6 inches per hour, and the maximum rate of snowfall recorded was 1.8 inches per hour. Which inequality is true for all values of $s$, where $s$ represents a rate of snowfall, in inches per hour, recorded for this snowstorm?','A) $s\\ge2.4$','B) $s\\ge1.8$','C) $0\\le s\\le0.6$','D) $0.6\\le s\\le1.8$']),
  13:q(['$$\\begin{aligned}y&=4x\\\\y&=x^2-12\\end{aligned}$$','A solution to the given system of equations is $(x,y)$, where $x>0$. What is the value of $x$?']),
  14:q(['A store sells two different-sized containers of blueberries. The store’s sales of these blueberries totaled 896.86 dollars last month. The equation $4.51x+6.07y=896.86$ represents this situation, where $x$ is the number of smaller containers sold and $y$ is the number of larger containers sold. According to the equation, what is the price, in dollars, of each smaller container?']),
  15:q(['A right circular cylinder has a base diameter of 22 centimeters and a height of 6 centimeters. What is the volume, in cubic centimeters, of the cylinder?','A) $132\\pi$','B) $264\\pi$','C) $726\\pi$','D) $2{,}904\\pi$']),
  16:{lines:[],imageFallback:true},
  17:q(['At a particular track meet, the ratio of coaches to athletes is 1 to 26. If there are $x$ coaches at the track meet, which of the following expressions represents the number of athletes at the track meet?','A) $\\frac{x}{26}$','B) $26x$','C) $x+26$','D) $\\frac{26}{x}$']),
  18:q(['Kaylani used fabric measuring 5 yards in length to make each suit for a men’s choir. The relationship between the number of suits that Kaylani made, $x$, and the total length of fabric that she purchased, $y$, in yards, is represented by the equation $y-5x=6$. What is the best interpretation of 6 in this context?','A) Kaylani made 6 suits.','B) Kaylani purchased a total of 6 yards of fabric.','C) Kaylani used a total of 6 yards of fabric to make the suits.','D) Kaylani purchased 6 yards more fabric than she used to make the suits.']),
  19:q(['What is the value of $\\tan\\left(\\frac{92\\pi}{3}\\right)$?','A) $-\\sqrt{3}$','B) $-\\frac{\\sqrt{3}}{3}$','C) $\\frac{\\sqrt{3}}{3}$','D) $\\sqrt{3}$']),
  20:q(['Note: Figure not drawn to scale.','In the triangle shown, what is the value of $\\cos x^\\circ$?'],true),
  21:q(['The function $g$ is defined by $g(x)=(x+14)(t-x)$, where $t$ is a constant. In the $xy$-plane, the graph of $y=g(x)$ passes through the point $(24,0)$. What is the value of $g(0)$?']),
  22:q(['$$(x+4)^2+(y-19)^2=121$$','The graph of the given equation is a circle in the $xy$-plane. The point $(a,b)$ lies on the circle. Which of the following is a possible value for $a$?','A) −16','B) −14','C) 11','D) 19']),
  23:q(['A right rectangular prism has a height of 9 inches. The length of the prism’s base is $x$ inches, which is 7 inches more than the width of the prism’s base. Which function $V$ gives the volume of the prism, in cubic inches, in terms of the length of the prism’s base?','A) $V(x)=x(x+9)(x+7)$','B) $V(x)=x(x+9)(x-7)$','C) $V(x)=9x(x+7)$','D) $V(x)=9x(x-7)$']),
  24:q(['Which of the following functions has(have) a minimum value at −3?','I. $f(x)=-6(3)^x-3$','II. $g(x)=-3(6)^x$','A) I only','B) II only','C) I and II','D) Neither I nor II']),
  25:q(['The result of increasing the quantity $x$ by 400% is 60. What is the value of $x$?','A) 12','B) 15','C) 240','D) 340']),
  26:q(['The function $f$ is defined by $f(x)=ax^2+bx+c$, where $a$, $b$, and $c$ are constants. The graph of $y=f(x)$ in the $xy$-plane passes through the points $(7,0)$ and $(-3,0)$. If $a$ is an integer greater than 1, which of the following could be the value of $a+b$?','A) −6','B) −3','C) 4','D) 5']),
  27:q(['The function $g$ is defined by $g(x)=x(x-2)(x+6)^2$. The value of $g(7-w)$ is 0, where $w$ is a constant. What is the sum of all possible values of $w$?']),
}

export function verifiedPracticeTest5Math1Content(questionNumber:number){return VERIFIED_PRACTICE_TEST_5_MATH1[questionNumber]}
