export type VerifiedPracticeTest6ReadingContent={lines:string[];needsVisual?:boolean}
const q=(lines:string[],needsVisual=false):VerifiedPracticeTest6ReadingContent=>({lines,needsVisual})

export const VERIFIED_PRACTICE_TEST_6_READING2:Record<number,VerifiedPracticeTest6ReadingContent>={
  1:q([
    'The works of Chicana artist Ester Hernandez are now _______ in museums both in the United States and abroad, but the murals she contributed to as a member of Las Mujeres Muralistas early in her artistic career were displayed in outdoor public spaces across San Francisco.',
    'Which choice completes the text with the most logical and precise word or phrase?',
    'A) invented',
    'B) adjusted',
    'C) featured',
    'D) recommended',
  ]),  2:q([
    'Whether Carmen Lomas Garza is creating small paintings and illustrations or large public artworks—such as Baile, a copper cutout of traditional Mexican dance in the San Francisco International Airport—she is _______ direct experience, drawing from memories of her childhood in Texas or details of her current surroundings in California.',
    'Which choice completes the text with the most logical and precise word or phrase?',
    'A) complimented by',
    'B) uncertain about',
    'C) unbothered by',
    'D) inspired by',
  ]),  3:q([
    'Animal researcher Amalia P.M. Bastos led a 2021 study about a wild kea parrot that used small stones as tools to preen its feathers. Skeptical colleagues had initially suggested to Bastos that the kea’s interactions with the stones might simply be _______ , but Bastos and her team showed that the kea was using the stones deliberately.',
    'Which choice completes the text with the most logical and precise word or phrase?',
    'A) intriguing',
    'B) obvious',
    'C) accidental',
    'D) observable',
  ]),  4:q([
    'In 1891, design artist William Morris cofounded the Kelmscott Press, which printed editions of books using preindustrial methods. Historians argue that Morris’s repudiation of industrialization is _______ the Kelmscott editions’ use of handmade materials and intricate ornamentation reminiscent of medieval manuscripts: these meticulously handcrafted elements exemplify the artistry involved.',
    'Which choice completes the text with the most logical and precise word or phrase?',
    'A) insensible to',
    'B) manifest in',
    'C) scrutinized by',
    'D) complicated by',
  ]),  5:q([
    'Mary Engle Pennington, a chemist who helped advance home refrigeration, undoubtedly made a substantial impact on society, but her place in our historical memory is perhaps more _______ than that of Stephanie Kwolek, who invented the incredibly strong material known as Kevlar, an accomplishment for which she will long be remembered.',
    'Which choice completes the text with the most logical and precise word or phrase?',
    'A) permanent',
    'B) tentative',
    'C) warranted',
    'D) prominent',
  ]),  6:q([
    'The following text is from Betty Smith’s 1943 novel A Tree Grows in Brooklyn. Francie, a young girl, visits the library often.',
    '[[SAT_PARAGRAPH_BREAK]]',
    'Francie thought that all the books in the world were in that library and she had a plan about reading all the books in the world. She was reading a book a day in alphabetical order and not skipping the dry ones. She remembered that the first author had been Abbott. She had been reading a book a day for a long time now and she was still in the B’s. Already she had read about bees and buffaloes, Bermuda vacations and Byzantine architecture. For all her enthusiasm, she had to admit that some of the B’s had been hard going. But Francie was a reader.',
    'Which choice best states the main purpose of the text?',
    'A) To illustrate Francie’s enjoyment of an unusual topic',
    'B) To explain why Francie prefers reading over other activities',
    'C) To portray Francie’s determination to meet a goal',
    'D) To describe a book that Francie greatly admires',
  ]),  7:q([
    'Researchers have long hypothesized that woolly mammoths were hunted to extinction in North America by humans using spears with grooved tips known as Clovis points. One anthropologist set out to test this hypothesis. Using a mechanical spear-thrower, he launched spears with Clovis points into mounds of clay—substitutes for the animals’ large bodies. The projectiles generally penetrated only a few inches into the clay, an amount insufficient to have harmed most woolly mammoths. This led the anthropologist to conclude that hunters using spears with Clovis points likely weren’t the principal drivers of the extinction.',
    'Which choice best states the main purpose of the text?',
    'A) To argue for the significance of new findings amid an ongoing debate among researchers',
    'B) To discuss the advantages and disadvantages of the method used in an experiment',
    'C) To summarize two competing hypotheses and a major finding associated with each one',
    'D) To describe an experiment whose results cast doubt on an established hypothesis',
  ]),  8:q([
    'The people of medieval Europe have traditionally been seen as uninterested in cleanliness and hygiene, but modern research has shown that this is largely a myth. According to historian Eleanor Janega, most medieval towns in Europe had at least one public bathhouse, which often offered both full-immersion baths and—more affordably—steam baths. While such amenities were available mainly to town dwellers, regular bathing in rivers and streams or daily sponge baths at home were common practices throughout medieval Europe.',
    'Which choice best describes the function of the underlined portion?',
    'A) It asserts that in medieval Europe steam baths were more popular in rural areas than in urban ones.',
    'B) It describes a limitation of earlier historians’ studies of medieval European bathing habits.',
    'C) It concedes that not all people in medieval Europe had access to public bathhouses.',
    'D) It explains why Janega decided to study the popularity of public bathhouses in medieval Europe.',
  ]),  9:q([
    'Scholarly accounts of the Chicano movement—a movement that advocated for the social, political, and cultural empowerment of Mexican Americans and reached its zenith in the 1960s and 1970s—tend to focus on the most militant, outspoken figures in the movement, making it seem uniformly radical. Geographer Juan Herrera has shown, however, that if we shift our focus toward the way the movement manifested in comparatively low-profile neighborhood institutions and projects, we see participants espousing an array of political orientations and approaches to community activism.',
    'Which choice best describes the function of the underlined portion in the text as a whole?',
    'A) It presents a trend in scholarship on the Chicano movement that the text claims has been reevaluated by researchers in light of Herrera’s work on the movement’s participants.',
    'B) It identifies an aspect of the Chicano movement that the text implies was overemphasized by scholars due to their own political orientations.',
    'C) It describes a common approach to studying the Chicano movement that, according to the text, obscures the ideological diversity of the movement’s participants.',
    'D) It summarizes the conventional method for analyzing the Chicano movement, which the text suggests creates a misleading impression of the effectiveness of neighborhood institutions and projects.',
  ]),  10:q([
    'Elizabeth Asiedu has identified a negative correlation between the share of developing countries’ economies derived from natural-resource extraction and those countries’ receipts of foreign investment. This may appear counterintuitive—resource extraction requires initial investments (in extractive technology, for instance) at scales best met by multinational corporations—but Asiedu notes that natural-resource industries’ boom-bust cycle can destabilize local currencies and increase developing countries’ vulnerability to external shocks, creating levels of uncertainty to which foreign investors are typically averse.',
    'Which choice best states the main idea of the text?',
    'A) Although it may seem surprising that foreign investment declines in developing countries as natural-resource extraction makes up a larger share of those countries’ economies, that decline happens because resource extraction requires initial investments too large for foreign investors to supply.',
    'B) Although developing countries tend to become less dependent on foreign investment as natural-resource industries make up a larger share of their economies, this change may not occur if the boom-bust cycle of those industries destabilizes local currencies or increases countries’ vulnerability to external shocks.',
    'C) Although one might expect that foreign investment would increase as natural-resource extraction makes up a larger share of developing countries’ economies, the opposite happens because heavy reliance on natural resources can lead to unattractive conditions for investors.',
    'D) Although foreign investors tend to avoid initial investments in natural-resource industries in developing countries, foreign investment may increase significantly as those industries stabilize and the risks associated with them decline.',
  ]),  11:q([
    'To understand how temperature change affects microorganism-mediated cycling of soil nutrients in alpine ecosystems, Eva Kaštovská et al. collected plant-soil cores in the Tatra Mountains at elevations around 2,100 meters and transplanted them to elevations of 1,700–1,800 meters, where the mean air temperature was warmer by 2°C. Microorganism-mediated nutrient cycling was accelerated in the transplanted cores; crucially, microorganism community composition was unchanged, allowing Kaštovská et al. to attribute the acceleration to temperature-induced increases in microorganism activity.',
    'It can most reasonably be inferred from the text that the finding about the microorganism community composition was important for which reason?',
    'A) It provided preliminary evidence that microorganism-mediated nutrient cycling was accelerated in the transplanted cores.',
    'B) It suggested that temperature-induced changes in microorganism activity may be occurring at increasingly high elevations.',
    'C) It ruled out a potential alternative explanation for the acceleration in microorganism-mediated nutrient cycling.',
    'D) It clarified that microorganism activity levels in the plant-soil cores varied depending on which microorganisms comprised the community.',
  ]),  12:q([
    'Some astronomers searching for extraterrestrial life have proposed that atmospheric NH₃ (ammonia) can serve as a biosignature gas—an indication that a planet harbors life. Jingcheng Huang, Sara Seager, and colleagues evaluated this possibility, finding that on rocky planets, atmospheric NH₃ likely couldn’t reach detectably high levels in the absence of biological activity. But the team also found that on so-called mini-Neptunes—gas planets smaller than Neptune but with atmospheres similar to Neptune’s—atmospheric pressure and temperature can be high enough to produce atmospheric NH₃.',
    'Based on the text, Huang, Seager, and colleagues would most likely agree with which statement about atmospheric NH₃?',
    'A) Its presence is more likely to indicate that a planet is a mini-Neptune than that the planet is a rocky planet that could support life.',
    'B) Its absence from a planet that’s not a mini-Neptune indicates that the planet probably doesn’t have life.',
    'C) It should be treated as a biosignature gas if detected in the atmosphere of a rocky planet but not if detected in the atmosphere of a mini-Neptune.',
    'D) It doesn’t reliably reach high enough concentrations in the atmospheres of rocky planets or mini-Neptunes to be treated as a biosignature gas.',
  ]),  13:q([
    'In 2021, four of the United States national parks that were among the most visited were Grand Canyon National Park, Rocky Mountain National Park, Yellowstone National Park, and Zion National Park. The graph shows the number of visits for recreation to each of these parks during the three-month period with the highest number of visitors. A student notes that among the parks shown in the graph, the park with the highest monthly recreation visits in all three months was _______',
    'Which choice most effectively uses data from the graph to complete the text?',
    'A) Zion National Park.',
    'B) Rocky Mountain National Park.',
    'C) Yellowstone National Park.',
    'D) Grand Canyon National Park.',
  ],true),  14:q([
    '“Lines Written in Early Spring” is a 1798 poem by William Wordsworth. In the poem, the speaker describes having contradictory feelings while experiencing the sights and sounds of a spring day: _______',
    'Which quotation from “Lines Written in Early Spring” most effectively illustrates the claim?',
    'A) “Through primrose-tufts, in that sweet bower, / The periwinkle trail’d its wreathes; / And ’tis my faith that every flower / Enjoys the air it breathes.”',
    'B) “The budding twigs spread out their fan, / To catch the breezy air; / And I must think, do all I can, / That there was pleasure there.”',
    'C) “The birds around me hopp’d and play’d: / Their thoughts I cannot measure, / But the least motion which they made, / It seem’d a thrill of pleasure.”',
    'D) “I heard a thousand blended notes, / While in a grove I [sat] reclined, / In that sweet mood when pleasant thoughts / Bring sad thoughts to the mind.”',
  ]),  15:q([
    'Mean Ratings for Patients after 21 Days',
    'Measure	Mean rating for participants aware of taking a placebo	Mean rating for participants in the control group',
    'Global improvement	5.0	3.9',
    'Symptom severity reduction	92.00	46.00',
    'Quality of life improvement	11.4	5.4',
    'To test whether a medication is effective, scientists compare outcomes for patients taking it and patients taking a placebo (a medically inactive substance). Patients normally aren’t told they’re receiving a placebo, but a research team conducted a study to see if there might be a medical benefit to telling them. The team used various measures to evaluate participants, with higher ratings indicating greater well-being in each measure. Compared to the mean ratings after 21 days for participants in the control group, the mean ratings for participants who were aware of taking a placebo _______',
    'Which choice most effectively uses data from the table to complete the statement?',
    'A) ranged from 5.0 to 92.00, indicating that well-being varied widely from participant to participant.',
    'B) were lower for two measures, with the rating for only one measure indicating greater well-being for these participants.',
    'C) ranged from 3.9 to 46.00, with no rating indicating greater well-being in any measure for these participants.',
    'D) were higher for all three measures, indicating greater overall well-being for these participants.',
  ]),  16:q([
    'As media consumption has become increasingly multiplatform and socially mediated, active news acquisition has diminished in favor of an attitude known as “news finds me” (NFM), in which people passively rely on their social networks and ambient media environments for information about current events. Homero Gil de Zúñiga and Trevor Diehl examined data on a representative group of adults in the United States to determine participants’ strength of NFM attitude, political knowledge, and political interest. Although no major election took place sufficiently near the study for Gil de Zúñiga and Diehl to identify causality between NFM and voting behavior, they did posit that NFM may reduce voting probability through an indirect effect.',
    'Which finding, if true, would most directly support the idea advanced by Gil de Zúñiga and Diehl?',
    'A) NFM attitude tends to increase in strength as major elections approach, and people are significantly more likely to vote in major elections than in minor elections.',
    'B) NFM attitude has a strong negative effect on political knowledge and interest, and there is known to be a strong positive correlation between political knowledge and interest and the likelihood of voting.',
    'C) Political interest is known to have a strong positive effect on likelihood of voting but shows only a weak positive effect on political knowledge, and NFM attitude shows little correlation with either political knowledge or political interest.',
    'D) The likelihood of voting increases as political knowledge increases, and the relationship between NFM attitude and political knowledge tends to strengthen as the size of people’s social networks increases.',
  ]),  17:q([
    'The practice of logging (cutting down trees for commercial and other uses) is often thought to be at odds with forest conservation (the work of preserving forests). However, a massive study in forest management and preservation spanning 700,000 hectares in Oregon’s Malheur National Forest calls that view into question. So far, results of the study suggest that forest plots that have undergone limited logging (the careful removal of a controlled number of trees) may be more robust than plots that haven’t been logged at all. These results, in turn, suggest that _______',
    'Which choice most logically completes the text?',
    'A) logging may be useful for maintaining healthy forests, provided it is limited.',
    'B) other forest management strategies are more effective than limited logging.',
    'C) as time passes, it will be difficult to know whether limited logging has any benefits.',
    'D) the best way to support forest health may be to leave large forests entirely untouched.',
  ]),  18:q([
    'Even with the widespread adoption of personal computers, many authors still choose to write and revise their novels by hand and only then transcribe the final version on a computer. It may be tempting to speculate about how a novel written this way would be affected if it had been exclusively typed instead, but each novel is a unique entity resulting from a specific set of circumstances. Therefore, _______',
    'Which choice most logically completes the text?',
    'A) in order to increase their efficiency, authors who currently write their novels largely by hand should instead work only on a computer.',
    'B) authors who do most of their drafting and revising by hand likely have more success than those who work entirely on a computer.',
    'C) novels written by hand take less time to produce, on average, than novels written on a computer do.',
    'D) there is no way to reasonably evaluate how a work would be different if it had been written by other means.',
  ]),  19:q([
    'In forecasting weather events, meteorologists sometimes discuss the role of atmospheric rivers. What are atmospheric rivers, and how _______ Part of the water cycle, atmospheric rivers are narrow channels of moisture moving through the atmosphere. In certain conditions, these “rivers” can release some of their moisture as precipitation.',
    'Which choice completes the text so that it conforms to the conventions of Standard English?',
    'A) do they affect our weather.',
    'B) they do affect our weather.',
    'C) do they affect our weather?',
    'D) they do affect our weather?',
  ]),  20:q([
    'One of the few African American global explorers during the turn of the 20th century, _______',
    'Which choice completes the text so that it conforms to the conventions of Standard English?',
    'A) Matthew Henson made several treks across Greenland between 1891 and 1909.',
    'B) 1891 and 1909 were the years between which Matthew Henson made several treks across Greenland.',
    'C) Greenland was where Matthew Henson made several treks between 1891 and 1909.',
    'D) several treks across Greenland were made by Matthew Henson between 1891 and 1909.',
  ]),  21:q([
    'Woven from recycled yarn and hand tufted using a carpet weaving technique passed down by the artist’s Turkish grandmother, _______ so lush and tactilely inviting that you are tempted to reach out and touch them.',
    'Which choice completes the text so that it conforms to the conventions of Standard English?',
    'A) the topological tapestries of Argentine textile artist Alexandra Kehayoglou are',
    'B) the Argentine textile artist Alexandra Kehayoglou creates topological tapestries that are',
    'C) when she creates her topological tapestries, Argentine textile artist Alexandra Kehayoglou makes them',
    'D) Alexandra Kehayoglou is an Argentine textile artist whose topological tapestries are',
  ]),
}

export function verifiedPracticeTest6Reading2Content(questionNumber:number){return VERIFIED_PRACTICE_TEST_6_READING2[questionNumber]}
