import {useEffect,useState} from 'react'
import {BarChart3,BookOpen,Clock3,Settings as SettingsIcon,Sparkles,Target,Upload} from 'lucide-react'
import PdfPage from './components/PdfPage'
import {QUESTION_BANK,moduleLabel,questionsForMode} from './lib/questionBank'
import {addAttempt,clearHistory,getAttempts,getSessions,getSettings,saveSession,saveSettings} from './lib/storage'
import {clearPdfs,getPdf,savePdf} from './lib/pdfStore'
import {syncAttempt,syncSession} from './lib/supabase'
import type {Attempt,PracticeQuestion,SessionSummary,Settings} from './types'
const uid=()=>crypto.randomUUID()
const fmt=(ms:number)=>{const s=Math.round(ms/1000);return s<60?`${s}s`:`${Math.floor(s/60)}m ${s%60}s`}
const norm=(v:string)=>v.trim().toLowerCase().replace(/\s+/g,'').replace('−','-')
const matches=(q:PracticeQuestion,a:string)=>q.correctAnswer.includes(' or ')?q.correctAnswer.split(' or ').some(x=>norm(x)===norm(a)):norm(q.correctAnswer)===norm(a)
function choose(settings:Settings,attempts:Attempt[]){const pool=questionsForMode(settings.mode);const stats=new Map<string,{n:number;c:number;last:number}>();attempts.forEach((a,i)=>{const s=stats.get(a.questionId)??{n:0,c:0,last:-1};s.n++;if(a.correct)s.c++;s.last=i;stats.set(a.questionId,s)});return pool.map(q=>{const s=stats.get(q.id);return{q,score:(s?0:1000)+(s?(1-s.c/s.n)*400:0)+(s?Math.min(200,attempts.length-s.last):0)+Math.random()*60}}).sort((a,b)=>b.score-a.score).slice(0,settings.questionsPerSession).map(x=>x.q)}
export default function App(){const[settings,setSettings]=useState<Settings>(()=>getSettings());const[qpdf,setQpdf]=useState<ArrayBuffer|null>(null);const[apdf,setApdf]=useState<ArrayBuffer|null>(null);const[attempts,setAttempts]=useState<Attempt[]>(()=>getAttempts());const[sessions,setSessions]=useState<SessionSummary[]>(()=>getSessions());const[qs,setQs]=useState<PracticeQuestion[]>([]);const[sid,setSid]=useState('');const[started,setStarted]=useState('');const[i,setI]=useState(0);const[qStart,setQStart]=useState(0);const[selected,setSelected]=useState('');const[submitted,setSubmitted]=useState(false);const[currentAttempts,setCurrentAttempts]=useState<Attempt[]>([]);const[view,setView]=useState<'home'|'practice'|'results'|'stats'|'settings'>('home');useEffect(()=>{Promise.all([getPdf('questions'),getPdf('answers')]).then(([q,a])=>{setQpdf(q);setApdf(a)})},[]);useEffect(()=>saveSettings(settings),[settings]);const current=qs[i];const accuracy=attempts.length?Math.round(100*attempts.filter(a=>a.correct).length/attempts.length):0;const avg=attempts.length?attempts.reduce((s,a)=>s+a.elapsedMs,0)/attempts.length:0
async function upload(kind:'questions'|'answers',f?:File){if(!f)return;await savePdf(kind,f);const b=await getPdf(kind);kind==='questions'?setQpdf(b):setApdf(b)}
function start(){const set=choose(settings,attempts);setQs(set);setSid(uid());setStarted(new Date().toISOString());setCurrentAttempts([]);setI(0);setSelected('');setSubmitted(false);setQStart(Date.now());setView('practice')}
async function record(correct:boolean,selfGraded=false){if(!current)return;const a:Attempt={id:uid(),sessionId:sid,questionId:current.id,subject:current.subject,module:current.module,questionNumber:current.number,selectedAnswer:selected,correctAnswer:current.correctAnswer,correct,selfGraded,elapsedMs:Date.now()-qStart,createdAt:new Date().toISOString()};addAttempt(a);setAttempts(p=>[...p,a]);setCurrentAttempts(p=>[...p,a]);void syncAttempt(a)}
async function submit(){if(!current||!selected.trim())return;setSubmitted(true);if(current.responseType==='multiple-choice')await record(matches(current,selected))}
async function next(){if(!currentAttempts.some(a=>a.questionId===current?.id))return;if(i+1>=qs.length){const s:SessionSummary={id:sid,startedAt:started,endedAt:new Date().toISOString(),mode:settings.mode,questionCount:qs.length,attempts:currentAttempts};saveSession(s);setSessions(p=>[...p,s]);void syncSession(s);setView('results');return}setI(x=>x+1);setSelected('');setSubmitted(false);setQStart(Date.now())}
if(!qpdf||!apdf)return <main className="shell"><section className="card upload"><div className="logo"><Sparkles/> SAT Daily</div><h1>Daily SAT practice from your own PDFs.</h1><p>Upload the practice test and answer-explanation PDFs. They stay on this device in browser storage and are not committed to GitHub.</p><div className="uploads"><label><Upload/><b>Practice test PDF</b><input type="file" accept="application/pdf" onChange={e=>upload('questions',e.target.files?.[0])}/></label><label><Upload/><b>Answer explanations PDF</b><input type="file" accept="application/pdf" onChange={e=>upload('answers',e.target.files?.[0])}/></label></div></section></main>
if(view==='practice'&&current){const rec=currentAttempts.find(a=>a.questionId===current.id);return <main className="practice"><header><button onClick={()=>setView('home')}><Sparkles/> SAT Daily</button><div>Question {i+1} of {qs.length}<progress value={i+1} max={qs.length}/></div><span>{moduleLabel(current.module)} · Q{current.number}</span></header><div className="practice-grid"><section className="pdf-card"><div className="focus"><b>Question {current.number}</b></div><PdfPage pdfKey="questions" bytes={qpdf} page={current.sourcePage} label={`${moduleLabel(current.module)} · Question ${current.number}`} questionNumber={current.number} cropToQuestion/></section><aside className="answer"><h2>Your answer</h2>{current.responseType==='multiple-choice'?<div className="choices">{['A','B','C','D'].map(c=><button disabled={submitted} className={selected===c?'selected':''} onClick={()=>setSelected(c)} key={c}>{c}</button>)}</div>:<input disabled={submitted} value={selected} onChange={e=>setSelected(e.target.value)} placeholder="Type your answer"/>}{!submitted&&<button className="primary" disabled={!selected.trim()} onClick={submit}>Submit answer</button>}{submitted&&current.responseType==='student-produced'&&!rec&&<div className="feedback">Official answer: <b>{current.correctAnswer}</b><div><button onClick={()=>record(true,true)}>I got it right</button><button onClick={()=>record(false,true)}>I got it wrong</button></div></div>}{rec&&<div className={rec.correct?'feedback good':'feedback bad'}><b>{rec.correct?'Correct':'Not quite'}</b><span>Correct answer: {current.correctAnswer} · {fmt(rec.elapsedMs)}</span></div>}{submitted&&settings.showExplanations&&<details open><summary>Official explanation</summary><PdfPage pdfKey="answers" bytes={apdf} page={current.answerPage} label="Answer explanations"/></details>}{rec&&<button className="primary" onClick={next}>{i+1===qs.length?'Finish session':'Next question'}</button>}</aside></div></main>}
if(view==='results'){const a=currentAttempts.length?Math.round(100*currentAttempts.filter(x=>x.correct).length/currentAttempts.length):0;const t=currentAttempts.length?currentAttempts.reduce((s,x)=>s+x.elapsedMs,0)/currentAttempts.length:0;return <main className="shell"><Nav current="" setView={setView}/><section className="card results"><p className="eyebrow">Session complete</p><h1>{a}% accuracy</h1><p>{currentAttempts.filter(x=>x.correct).length} of {currentAttempts.length} correct · {fmt(t)} average</p><h3>Slowest questions</h3>{[...currentAttempts].sort((x,y)=>y.elapsedMs-x.elapsedMs).slice(0,3).map(x=><div className="row" key={x.id}><span>{moduleLabel(x.module)} Q{x.questionNumber}</span><b>{fmt(x.elapsedMs)}</b><span>{x.correct?'Correct':'Review'}</span></div>)}<button className="primary" onClick={start}>Start another session</button></section></main>}
if(view==='stats')return <main className="shell"><Nav current="stats" setView={setView}/><h1>Your practice trends</h1><div className="stats"><Stat icon={<Target/>} label="Accuracy" value={attempts.length?`${accuracy}%`:'—'}/><Stat icon={<Clock3/>} label="Avg. time" value={attempts.length?fmt(avg):'—'}/><Stat icon={<BookOpen/>} label="Sessions" value={String(sessions.length)}/><Stat icon={<BarChart3/>} label="Questions seen" value={`${new Set(attempts.map(a=>a.questionId)).size}/${QUESTION_BANK.length}`}/></div><section className="card"><h2>Recent sessions</h2>{sessions.slice().reverse().slice(0,10).map(s=><div className="row" key={s.id}><span>{new Date(s.endedAt).toLocaleDateString()}</span><b>{Math.round(100*s.attempts.filter(a=>a.correct).length/Math.max(1,s.attempts.length))}%</b><span>{s.questionCount} questions · {s.mode}</span></div>)}</section></main>
if(view==='settings')return <main className="shell"><Nav current="settings" setView={setView}/><h1>Practice setup</h1><section className="card settings"><label>Subject<select value={settings.mode} onChange={e=>setSettings({...settings,mode:e.target.value as Settings['mode']})}><option value="both">English + Math</option><option value="english">English only</option><option value="math">Math only</option></select></label><label>Questions per session<input type="number" min="3" max="30" value={settings.questionsPerSession} onChange={e=>setSettings({...settings,questionsPerSession:Math.max(3,Math.min(30,+e.target.value))})}/></label><label><input type="checkbox" checked={settings.showExplanations} onChange={e=>setSettings({...settings,showExplanations:e.target.checked})}/> Show explanations after answering</label><div><button onClick={()=>{clearHistory();setAttempts([]);setSessions([])}}>Clear statistics</button><button onClick={async()=>{await clearPdfs();setQpdf(null);setApdf(null)}}>Replace PDFs</button></div></section></main>
return <main className="shell"><Nav current="home" setView={setView}/><section className="hero card"><div><p className="eyebrow">Daily SAT practice</p><h1>Small sessions. Clear feedback. Real progress.</h1><p>Today’s set prioritizes unseen questions and questions you previously missed.</p><button className="primary" onClick={start}>Start {settings.questionsPerSession}-question session</button></div><div className="score">{attempts.length?`${accuracy}%`:'—'}<small>overall accuracy</small></div></section><div className="stats"><Stat icon={<Target/>} label="Accuracy" value={attempts.length?`${accuracy}%`:'—'}/><Stat icon={<Clock3/>} label="Avg. time" value={attempts.length?fmt(avg):'—'}/><Stat icon={<BookOpen/>} label="Sessions" value={String(sessions.length)}/><Stat icon={<Sparkles/>} label="Seen" value={`${new Set(attempts.map(a=>a.questionId)).size}/${QUESTION_BANK.length}`}/></div></main>}
function Nav({current,setView}:{current:string;setView:(v:'home'|'stats'|'settings')=>void}){return <nav><button className="logo" onClick={()=>setView('home')}><Sparkles/> SAT Daily</button><div><button className={current==='home'?'active':''} onClick={()=>setView('home')}>Dashboard</button><button className={current==='stats'?'active':''} onClick={()=>setView('stats')}>Stats</button><button className={current==='settings'?'active':''} onClick={()=>setView('settings')}><SettingsIcon size={16}/> Settings</button></div></nav>}
function Stat({icon,label,value}:{icon:React.ReactNode;label:string;value:string}){return <div className="stat">{icon}<span>{label}</span><b>{value}</b></div>}
