import {useEffect,useState} from 'react'
import {BarChart3,BookOpen,ChevronLeft,ChevronRight,Clock3,Settings as SettingsIcon,Sparkles,Target,Upload} from 'lucide-react'
import SourceSlice from './components/SourceSlice'
import AlexButton from './design-system/atoms/AlexButton'
import AlexChoiceButton from './design-system/atoms/AlexChoiceButton'
import AlexDropdown from './design-system/atoms/AlexDropdown'
import AlexNumberField from './design-system/atoms/AlexNumberField'
import AlexTextField from './design-system/atoms/AlexTextField'
import {QUESTION_BANK,moduleLabel,questionsForMode} from './lib/questionBank'
import {addAttempt,clearHistory,getAttempts,getSessions,getSettings,saveSession,saveSettings} from './lib/storage'
import {clearPdfs,getPdf,savePdf} from './lib/pdfStore'
import {syncAttempt,syncSession} from './lib/supabase'
import type {Attempt,PracticeQuestion,SessionSummary,Settings} from './types'

const uid=()=>crypto.randomUUID()
const fmt=(ms:number)=>{const s=Math.round(ms/1000);return s<60?`${s}s`:`${Math.floor(s/60)}m ${s%60}s`}
const norm=(v:string)=>v.trim().toLowerCase().replace(/\s+/g,'').replace('−','-')
const matches=(q:PracticeQuestion,a:string)=>q.correctAnswer.includes(' or ')?q.correctAnswer.split(' or ').some(x=>norm(x)===norm(a)):norm(q.correctAnswer)===norm(a)
function choose(settings:Settings,attempts:Attempt[]){const pool=questionsForMode(settings.mode);const stats=new Map<string,{n:number;c:number;last:number}>();attempts.forEach((a,i)=>{const s=stats.get(a.questionId)??{n:0,c:0,last:-1};s.n++;if(a.correct)s.c++;s.last=i;stats.set(a.questionId,s)});return pool.map(q=>{const s=stats.get(q.id);return{q,score:(s?0:1000)+(s?(1-s.c/s.n)*400:0)+(s?Math.min(200,attempts.length-s.last):0)+Math.random()*60}}).sort((a,b)=>b.score-a.score).slice(0,settings.questionsPerSession).map(x=>x.q)}

type View='home'|'practice'|'results'|'stats'|'settings'|'sources'

export default function App(){
  const[settings,setSettings]=useState<Settings>(()=>getSettings())
  const[qpdf,setQpdf]=useState<ArrayBuffer|null>(null)
  const[apdf,setApdf]=useState<ArrayBuffer|null>(null)
  const[attempts,setAttempts]=useState<Attempt[]>(()=>getAttempts())
  const[sessions,setSessions]=useState<SessionSummary[]>(()=>getSessions())
  const[qs,setQs]=useState<PracticeQuestion[]>([])
  const[sid,setSid]=useState('')
  const[started,setStarted]=useState('')
  const[i,setI]=useState(0)
  const[qStart,setQStart]=useState(0)
  const[selected,setSelected]=useState('')
  const[submitted,setSubmitted]=useState(false)
  const[currentAttempts,setCurrentAttempts]=useState<Attempt[]>([])
  const[view,setView]=useState<View>('home')

  useEffect(()=>{Promise.all([getPdf('questions'),getPdf('answers')]).then(([q,a])=>{setQpdf(q);setApdf(a)})},[])
  useEffect(()=>saveSettings(settings),[settings])

  const current=qs[i]
  const accuracy=attempts.length?Math.round(100*attempts.filter(a=>a.correct).length/attempts.length):0
  const avg=attempts.length?attempts.reduce((s,a)=>s+a.elapsedMs,0)/attempts.length:0
  const currentRec=current?currentAttempts.find(a=>a.questionId===current.id):undefined

  async function upload(kind:'questions'|'answers',f?:File){if(!f)return;await savePdf(kind,f);const b=await getPdf(kind);kind==='questions'?setQpdf(b):setApdf(b)}
  function start(){if(!qpdf){setView('sources');return}const set=choose(settings,attempts);setQs(set);setSid(uid());setStarted(new Date().toISOString());setCurrentAttempts([]);setI(0);setSelected('');setSubmitted(false);setQStart(Date.now());setView('practice')}
  async function record(correct:boolean,selfGraded=false){if(!current)return;const a:Attempt={id:uid(),sessionId:sid,questionId:current.id,subject:current.subject,module:current.module,questionNumber:current.number,selectedAnswer:selected,correctAnswer:current.correctAnswer,correct,selfGraded,elapsedMs:Date.now()-qStart,createdAt:new Date().toISOString()};addAttempt(a);setAttempts(p=>[...p,a]);setCurrentAttempts(p=>[...p,a]);void syncAttempt(a)}
  async function submit(){if(!current||!selected.trim()||currentRec)return;setSubmitted(true);if(current.responseType==='multiple-choice')await record(matches(current,selected))}
  function goTo(index:number){if(index<0||index>=qs.length)return;const q=qs[index];const rec=currentAttempts.find(a=>a.questionId===q.id);setI(index);setSelected(rec?.selectedAnswer??'');setSubmitted(!!rec);if(!rec)setQStart(Date.now())}
  async function finish(){const s:SessionSummary={id:sid,startedAt:started,endedAt:new Date().toISOString(),mode:settings.mode,questionCount:qs.length,attempts:currentAttempts};saveSession(s);setSessions(p=>[...p,s]);void syncSession(s);setView('results')}
  async function next(){if(!currentRec)return;if(i+1>=qs.length){await finish();return}goTo(i+1)}
  function resetHistory(){if(!window.confirm('Delete all practice history and statistics? Your settings and uploaded question sources will be kept.'))return;clearHistory();setAttempts([]);setSessions([]);setCurrentAttempts([]);setQs([]);setSid('');setStarted('');setI(0);setSelected('');setSubmitted(false);setView('home')}

  if(view==='practice'&&current&&qpdf)return <main className="practice">
    <header className="practice-topbar"><button className="logo practice-logo" onClick={()=>setView('home')}><Sparkles/> SAT Daily</button><div className="progress-block"><div><b>{moduleLabel(current.module)}</b><span>Question {i+1} of {qs.length}</span></div><progress value={i+1} max={qs.length}/></div><div className="question-nav"><AlexButton tone="secondary" startIcon={<ChevronLeft size={18}/>} onClick={()=>goTo(i-1)} disabled={i===0}>Previous</AlexButton><AlexButton endIcon={<ChevronRight size={18}/>} onClick={next} disabled={!currentRec}>{i+1===qs.length?'Finish':'Next'}</AlexButton></div></header>
    <div className="practice-workspace"><section className="question-panel"><div className="question-heading"><div><span>QUESTION {current.number}</span><b>{current.subject==='math'?'Math':'Reading & Writing'}</b></div><div className="status-chip">READY</div></div><SourceSlice pdfKey="questions" bytes={qpdf} page={current.sourcePage} questionNumber={current.number} alt={`${moduleLabel(current.module)} question ${current.number}`}/></section><aside className="answer-panel"><div><p className="answer-kicker">Your answer</p><h2>Choose the best answer.</h2><p className="answer-helper">Answer this question, then use Next to continue.</p></div>{current.responseType==='multiple-choice'?<div className="choices">{['A','B','C','D'].map(c=><AlexChoiceButton disabled={!!currentRec} selected={selected===c} onClick={()=>setSelected(c)} key={c} label={c}/>)}</div>:<AlexTextField disabled={!!currentRec||submitted} value={selected} onChange={e=>setSelected(e.target.value)} placeholder="Type your answer"/>}{!currentRec&&!submitted&&<AlexButton fullWidth disabled={!selected.trim()} onClick={submit}>Submit answer</AlexButton>}{submitted&&current.responseType==='student-produced'&&!currentRec&&<div className="feedback">Official answer: <b>{current.correctAnswer}</b><div><AlexButton tone="secondary" onClick={()=>record(true,true)}>I got it right</AlexButton><AlexButton tone="secondary" onClick={()=>record(false,true)}>I got it wrong</AlexButton></div></div>}{currentRec&&<div className={currentRec.correct?'feedback good':'feedback bad'}><b>{currentRec.correct?'Correct':'Not quite'}</b><span>Correct answer: {current.correctAnswer}</span><span>Time: {fmt(currentRec.elapsedMs)}</span></div>}<p className="review-note">Explanation will be available in your session review.</p></aside></div>
  </main>

  if(view==='results'){const a=currentAttempts.length?Math.round(100*currentAttempts.filter(x=>x.correct).length/currentAttempts.length):0;const t=currentAttempts.length?currentAttempts.reduce((s,x)=>s+x.elapsedMs,0)/currentAttempts.length:0;return <main className="shell"><Nav current="" setView={setView}/><section className="card results"><p className="eyebrow">Session complete</p><h1>{a}% accuracy</h1><p>{currentAttempts.filter(x=>x.correct).length} of {currentAttempts.length} correct · {fmt(t)} average</p><div className="review-list"><h2>Session review</h2>{currentAttempts.map((att,index)=>{const q=QUESTION_BANK.find(x=>x.id===att.questionId);if(!q)return null;return <article className="review-item" key={att.id}><div className="review-head"><div><b>{index+1}. {moduleLabel(att.module)} · Q{att.questionNumber}</b><span>{att.correct?'Correct':'Review'} · {fmt(att.elapsedMs)}</span></div><div><span>Your answer: <b>{att.selectedAnswer||'—'}</b></span><span>Correct: <b>{att.correctAnswer}</b></span></div></div>{apdf?<details><summary>Show official explanation</summary><SourceSlice pdfKey="answers" bytes={apdf} page={q.answerPage} questionNumber={q.number} alt={`Official explanation for question ${q.number}`}/></details>:<p className="muted">Add the answer-explanations source in Manage Sources to review explanations here.</p>}</article>})}</div><AlexButton onClick={start}>Start another session</AlexButton></section></main>}

  if(view==='stats')return <main className="shell"><Nav current="stats" setView={setView}/><div className="page-heading"><div><p className="eyebrow">History</p><h1>Your practice trends</h1></div>{attempts.length>0&&<AlexButton tone="secondary" onClick={resetHistory}>Clear history & start fresh</AlexButton>}</div><div className="stats"><Stat icon={<Target/>} label="Accuracy" value={attempts.length?`${accuracy}%`:'—'}/><Stat icon={<Clock3/>} label="Avg. time" value={attempts.length?fmt(avg):'—'}/><Stat icon={<BookOpen/>} label="Sessions" value={String(sessions.length)}/><Stat icon={<BarChart3/>} label="Questions seen" value={`${new Set(attempts.map(a=>a.questionId)).size}/${QUESTION_BANK.length}`}/></div>{attempts.length===0&&<section className="card empty-history"><h2>Fresh start</h2><p>No practice history is stored yet. Your next session will begin building new statistics.</p></section>}</main>

  if(view==='settings')return <main className="shell"><Nav current="settings" setView={setView}/><h1>Practice setup</h1><section className="card settings settings-grid"><div className="settings-field"><AlexDropdown id="practice-subject" label="Subject" value={settings.mode} options={[{value:'both',label:'English + Math'},{value:'english',label:'English only'},{value:'math',label:'Math only'}]} onChange={mode=>setSettings({...settings,mode})}/></div><div className="settings-field"><AlexNumberField label="Questions per session" value={settings.questionsPerSession} min={3} max={30} onChange={questionsPerSession=>setSettings({...settings,questionsPerSession})}/></div><div className="settings-actions"><AlexButton tone="secondary" onClick={resetHistory}>Clear history & start fresh</AlexButton></div><p className="muted">This removes saved attempts, sessions, accuracy, timing history, and question-selection history. Your settings and uploaded PDF sources are kept.</p></section></main>

  if(view==='sources')return <main className="shell"><Nav current="sources" setView={setView}/><h1>Manage sources</h1><section className="card sources"><p>Sources are used only to render each question or explanation as a clean image. There is no PDF viewer in practice mode.</p><div className="uploads"><label><Upload/><b>{qpdf?'Replace question source':'Add question source'}</b><span>{qpdf?'Ready for practice':'Required for exact question formatting'}</span><input type="file" accept="application/pdf" onChange={e=>upload('questions',e.target.files?.[0])}/></label><label><Upload/><b>{apdf?'Replace explanation source':'Add explanation source'}</b><span>{apdf?'Ready for session review':'Optional'}</span><input type="file" accept="application/pdf" onChange={e=>upload('answers',e.target.files?.[0])}/></label></div>{(qpdf||apdf)&&<AlexButton tone="secondary" onClick={async()=>{await clearPdfs();setQpdf(null);setApdf(null)}}>Clear sources</AlexButton>}</section></main>

  return <main className="app-shell"><aside className="side-nav"><button className="side-brand" onClick={()=>setView('home')}><Sparkles size={18}/> SAT</button><div className="side-links"><button className={view==='home'?'active':''} onClick={()=>setView('home')}>Study Plan</button><button className={view==='practice'?'active':''} onClick={start}>Practice Tests</button><button onClick={()=>setView('settings')}>Question Bank</button><button className={view==='stats'?'active':''} onClick={()=>setView('stats')}>Performance</button><span>ADDITIONAL TOOLS</span><button className={view==='sources'?'active':''} onClick={()=>setView('sources')}>Resources</button></div><div className="side-footer">SAT Daily</div></aside><section className="dashboard"><div className="dashboard-header"><p className="eyebrow">Practice Tests</p><h1>SAT Practice Tests</h1><p>Build a focused practice session, review your performance, and keep working on the questions that need the most attention.</p></div><div className="dashboard-divider"/><section className="practice-options"><div className="section-title"><h2>Practice Test Options</h2><p>Choose a full mixed session or focus on one SAT section.</p></div><div className="option-grid"><article className="option-card"><div className="option-card-title"><span className="option-dot"/><div><h3>Full practice session</h3><p>Reading & Writing + Math</p></div></div><div className="option-action"><div><span className="status-chip">READY</span><b>Start mixed SAT practice</b><small>{settings.questionsPerSession} questions using your adaptive question pool</small></div><AlexButton onClick={start}>Start</AlexButton></div></article><article className="option-card"><div className="option-card-title"><span className="option-dot half"/><div><h3>Single section practice</h3><p>Focus on one section at a time</p></div></div><div className="section-actions"><div className="option-action compact"><div><span className="status-chip">READY</span><b>Reading & Writing practice</b></div><AlexButton tone="secondary" onClick={()=>{setSettings({...settings,mode:'english'});setTimeout(start,0)}}>Start</AlexButton></div><div className="option-action compact"><div><span className="status-chip">READY</span><b>Math practice</b></div><AlexButton tone="secondary" onClick={()=>{setSettings({...settings,mode:'math'});setTimeout(start,0)}}>Start</AlexButton></div></div></article></div></section></section></main>
}

function Nav({current,setView}:{current:string;setView:(v:View)=>void}){return <nav><button className="logo" onClick={()=>setView('home')}><Sparkles/> SAT Daily</button><div><AlexButton tone={current==='home'?'secondary':'quiet'} onClick={()=>setView('home')}>Dashboard</AlexButton><AlexButton tone={current==='stats'?'secondary':'quiet'} onClick={()=>setView('stats')}>Stats</AlexButton><AlexButton tone={current==='settings'?'secondary':'quiet'} startIcon={<SettingsIcon size={16}/>} onClick={()=>setView('settings')}>Settings</AlexButton><AlexButton tone={current==='sources'?'secondary':'quiet'} startIcon={<Upload size={16}/>} onClick={()=>setView('sources')}>Manage Sources</AlexButton></div></nav>}
function Stat({icon,label,value}:{icon:React.ReactNode;label:string;value:string}){return <div className="stat">{icon}<span>{label}</span><b>{value}</b></div>}
